version: 2

models:
  - name: stg_green_tripdata
    columns:
      - name: payment_type
        tests:
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
                quote: false

  - name: stg_yellow_tripdata
    columns:
      - name: payment_type
        tests:
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
                quote: false

  - name: stg_fhv_tripdata
    columns:
      - name: dispatching_base_num

  - name: int_trips_unioned

  - name: dim_vendors

  - name: dim_locations

  - name: fct_trips

  - name: fct_monthly_zone_revenue
